import type { Metadata } from "next";
import "./globals.css";
import { Orbitron  } from "next/font/google";

const font = Orbitron({ subsets: ["latin"], weight: "500" });

export const metadata: Metadata = {
  title: "Snakes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}

